version: '3.9'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.12.0
    hostname: wazuh-manager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    configs:
      - source: root_ca_cert
        target: /etc/ssl/root-ca.pem
      - source: wazuh_manager_cert
        target: /etc/ssl/filebeat.pem
      - source: wazuh_manager_key
        target: /etc/ssl/filebeat.key
      - source: wazuh_manager_conf
        target: /path/inside/container/wazuh-manager.conf
      # - source: wait-for-indexer
        # target: /wait-for-indexer.sh
        # mode: 0444
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
    # entrypoint: ["/bin/sh", "/wait-for-indexer.sh"]
    networks:
      wazuh_net:
        aliases:
          - wazuh.manager
    depends_on:
      - wazuh.indexer

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.12.0
    hostname: wazuh-indexer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "9200:9200"
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    configs:
      - source: root_ca_cert_indexer
        target: /usr/share/wazuh-indexer/certs/root-ca.pem
      - source: wazuh_indexer_key
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - source: wazuh_indexer_cert
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - source: admin_cert
        target: /usr/share/wazuh-indexer/certs/admin.pem
      - source: admin_key
        target: /usr/share/wazuh-indexer/certs/admin-key.pem
      - source: wazuh_indexer_yml
        target: /usr/share/wazuh-indexer/opensearch.yml
      - source: internal_users_yml
        target: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      wazuh_net:
        aliases:
          - wazuh.indexer
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:SecretPassword https://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.12.0
    hostname: wazuh-dashboard
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "443:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    configs:
      - source: wazuh_dashboard_cert
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - source: wazuh_dashboard_key
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - source: root_ca_cert_dashboard
        target: /usr/share/wazuh-dashboard/certs/root-ca.pem
      - source: opensearch_dashboards_yml
        target: /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - source: wazuh_yml
        target: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    networks:
      wazuh_net:
        aliases:
          - wazuh.dashboard

networks:
  wazuh_net:
    driver: overlay

configs:
  root_ca_cert:
    external: true
  wazuh_manager_cert:
    external: true
  wazuh_manager_key:
    external: true
  wazuh_manager_conf:
    external: true
  root_ca_cert_indexer:
    external: true
  wazuh_indexer_key:
    external: true
  wazuh_indexer_cert:
    external: true
  admin_cert:
    external: true
  admin_key:
    external: true
  wazuh_indexer_yml:
    external: true
  internal_users_yml:
    external: true
  wazuh_dashboard_cert:
    external: true
  wazuh_dashboard_key:
    external: true
  root_ca_cert_dashboard:
    external: true
  opensearch_dashboards_yml:
    external: true
  wazuh_yml:
    external: true
  wait-for-indexer:
    external: true

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
