services:
  wazuh_certs_generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    deploy:
      restart_policy:
        condition: any
    networks:
      - wazuh_net

networks:
  wazuh_net:
    driver: overlay