nodes:
  indexer:
    - name: wazuh-indexer
      ip: wazuh-indexer
      dns:
        - wazuh.indexer
        - wazuh-indexer

  server:
    - name: wazuh-manager
      ip: wazuh-manager
      dns:
        - wazuh.manager
        - wazuh-manager

  dashboard:
    - name: wazuh-dashboard
      ip: wazuh-dashboard
      dns:
        - wazuh.dashboard
        - wazuh-dashboard
